config.w32

Hi Joe, I know it is work in progress, but if I want to follow the progress it might be welcome to fix config.w32 for the seven branch

Fix config.w32 for PHP7

---

INSTALL

Small documentation change regarding mmap

MMAP is compiled by default

---

README.md

It's not much, but it's a good start i think

Added contributing section to readme

---

php_apc.c

BugFix: https://bugs.php.net/bug.php?id=75718

Use row formatting for information in phpinfo() tables

---

apc.c
apc_iterator.c
php_apc.c
tests/iterator_008.phpt

Also add some derefs, fix a leak.

Cleanup hashtable iteration

---

apc_pool.c

GC_FLAGS() cannot be assigned to anymore.

Fix build against master

---

.travis.yml
apc.h
apc_globals.h
apc_iterator.c
php_apc.c
tests/iterator_010.phpt

This adds some infrastructure for testing TTLs (apcu_inc_request_time in debug builds) and implements the iterator related parts of #291.

Iterator TTL handling fixes

---

apc_cache.c
apc_cache_api.h
apc_iterator.c

At this point the distinction between slot and entry has become meaningless, so combine them into one structure. This saves one level of indirection, a pointer and lays out the structures in a more sensible manner (previously the entry came first, then any serialized data, then the slot; now the entry and slot are together, followed by the serialized data).

Unify slot and entry structures

---

apc.php

Detail/entry content then works for cache entries that are not on the first page of the unfiltered list.

Keep search parameter on cache entry detail link.

---

apc.php

with this change the header will stick at the top when scrolling thru all the table rows.
that way you always know which table column has which header.

Make the table header be rendered in a sticky fashion

---

apc.php

pecl.php.net supports HTTPS for a long time

Using HTTPS instead of HTTP

---

apc.php

Address https://github.com/krakjoe/apcu/pull/433#discussion_r801023324 review and use tabs for code style

PHP 8.1 compatibility

---

apc_persist.c

The pointer data apcu sees is usually aligned to 16 bytes on 64-bit systems using emalloc. It is guaranteed to be aligned to a power of at least ZEND_MM_ALIGNMENT_LOG2.
Preserve the original bits just in case, similar to opcache's zend_rotr3.
Benchmarking this for repeatedly unserializing large arrays with small strings and apc.serializer=default, this showed a moderate performance improvement. (note that apcu_fetch returns a different array on every call due to the possibility of cache evictions) (reducing cpu frequency to 2.5GHz to be the same for both tests)
For an array with 65536 small string keys and values and `apc.serializer=default`:
- Repeated apcu_fetch went from 3.5 seconds -> 3.0 seconds
- For an array with 4096 small string keys and values: Repeated apcu_fetch went from 1.2 …

Optimize unserializing arrays with apc.serializer=default

---

apc_persist.c

Also avoid hash collisions when computing the size of data

---

apc_persist.c

Reduce shared memory usage in php 7.3+ for `apc.serializer=default`. Store the pointer to the immutable zend_empty_array rather than a brand new array. (APCu is already storing a pointer to static variables elsewhere, e.g. uninitialized_bucket)

Reduce shared memory usage storing the empty array

---

tests/apc54_014.phpt
tests/ghbug176.phpt

Remove check in tests for php 5.4+

---

README.md

Follows-up https://github.com/krakjoe/apcu/pull/449.

Remove broken Travis badge from readme

---

composer.json

As per discussion https://github.com/krakjoe/apcu/pull/524#issuecomment-2359423616

Update vendor name to apcu for PIE

---

apc_mmap.c
apc_mmap.h
apc_shm.c
apc_shm.h
apc_sma.c

Better separation of the sma layer and the mmap / shm implementation.

Cleanup mmap and shm implementation

---

apc_sma.c

The removed code has been commented out with #if 0 since 2013-03-11 (commit 70aabadc). It has been dead code since the beginning of apcu.

Remove unused debug code from sma layer

---

TECHNOTES.txt

The technotes now describe the currently used structure of the sma layer with the initial 3 blocks and the doubly linked list.

Update TECHNOTES to current state of sma layer

---

apc_sma.c

The fprev field now stores the used memory size for allocated blocks. This is used during defragmentation to shrink the block if more memory has been allocated than necessary.

Reclaim unused space from allocated blocks during defragmentation
