apc_cache_api.h, config.w32
Silly fix: you were the only one that used ushort in stead of unsigned short. 'typedef unsigned short ushort;' would have been a solution, but better make it generic and use 'unsigned short' on all platforms.
And I added apc_windows_srwlock_kernel.c in config.w32.
php_apcu.dll compiles on Windows now as well. I did not run the tests yet, though.
=> Windows fixes

apc_cache.c
At the moment apcu_dec/inc() return FALSE when the entry they modify doesn't exist. This patch changes this behavior - they'll create missing entry and assign it 'step' value.
=> apcu_inc/dec should create missing cache entries

php_apc.c
The patch just fixes the code so that it would compile with PHP7.
But I must note that BC doesn't quite work - changing the module hash from within hash_apply() produces these warnings and a crash for me:
==32026== Invalid read of size 1
==32026==    at 0x63F3C0: zend_hash_apply (zend_hash.c:1459)
==32026==    by 0x631DF9: zend_startup_modules (zend_API.c:1955)
==32026==    by 0x5D00C5: php_module_startup (main.c:2194)
==32026==    by 0x6C64C4: php_cgi_startup (fpm_main.c:837)
==32026==    by 0x42DADC: main (fpm_main.c:1788)
==32026==  Address 0x74bbff8 is 8 bytes after a block of size 1,152 free'd
==32026==    at 0x4C2970C: free (vg_replace_malloc.c:468)
==32026==    by 0x6391C4: zend_hash_do_resize (zend_hash.c:825)
==32026==    by 0x639BB7: _zend_hash_add (zend_hash.c:536)
==32026== …
=> Fixed build with BC disabled 

config.m4
This patch fixes those cases, enabling mmap and rwlocks by default.
```sh
$ ./configure | grep rwlocks
checking if APCu should be allowed to use rwlocks... yes
configure: WARNING: APCu has access to native rwlocks
$ ./configure --enable-apcu-rwlocks | grep rwlocks
checking if APCu should be allowed to use rwlocks... no
configure: WARNING: APCu has access to mutexes
$ ./configure --disable-apcu-rwlocks | grep rwlocks
checking if APCu should be allowed to use rwlocks... no
configure: WARNING: APCu has access to mutexes
$ ./configure | grep mmap
checking if APCu will use mmap or shm... mmap
$ ./configure --enable-apcu-mmap | grep mmap
checking if APCu will use mmap or shm... shm
$ ./configure --disable-apcu-mmap | grep mmap
checking if APCu will use mmap or shm... shm
```
```sh
$ ./configure …
```
=> Fix config.m4 --enable-apcu-{rwlocks,mmap}

README.md
The first line of the readme should explain what APCu is.
The old explanation was only sufficient for people who know APC.
The new explanation keeps the comparison to the original APC,
but it explains clearer what the actual purpose of APCu is.
Some new users may find APCu and have never heard of APC.
=> Readme starts with independent explanation of APCu

apc_cache.c, tests/apc_005b.phpt, tests/apc_005c.phpt
Affects built in serializer as well as the igbinary7 serializer.
The apc serialization/unserialization code was checking
IS_REFCOUNTED_P(val).
However, when objects were being serialized as strings, the 
IS_REFCOUNTED bit in the type flags wasn't being set (Bitmask was 0)
This meant that if there were two uses of an object being serialized, it would be
cloned, since the code treated `dst` as if it couldn't be refcounted, and 
thus didn't add the mapping from `src`'s zend_refcounted pointer to `dst` into
`si->copied`
Found this bug while working on https://github.com/igbinary/igbinary7/pull/23
=> Fix memory leak/failed check for duplicates when serializing arrays and object

apc_cache.c
That type is used by the type checker, and isn't a zval type.
https://wiki.php.net/phpng-int
> IS_CALLABLE – used only for type hinting
> _IS_BOOL – used_only for type hinting
=> Remove IS_CALLABLE check - zvals never have that type.

.travis.yml
7.1 was a supported release tag for a few weeks during the RCs.
7.1.0 was released on Friday.
`nightly` is similar to `7.2-dev`, so I left it in.
=> Add 7.1 to the travis.yml

apc.php
- The usage of each(), next() was hard to read.
(Those functions may be deprecated in the future)
Use a for loop instead.
This was tested locally
=> Update the apc dashboard : stop using each(), next()

php_apc.c, tests/apc_016.phpt
=> Allow passing a reference to a string (in an array) to apcu_fetch

php_apc.c, tests/apc_099.phpt
If a non refcountable type is a member of that array(e.g. null, int,
float, bool), then APCu would emit a warning, then crash.
Z_TRY_ADDREF will check if something has a reference before attempting
to increment the part of the zval that points to the reference.
This PR includes a test case that would previously cause a segfault.
Found when trying to figure out what apcu_delete does in edge cases
=> Fix crash when passing bad array to apcu_delete

apc_iterator.c, tests/apc_001.phpt, tests/apc_002.phpt, tests/apc_003b.phpt, tests/apc_004.phpt, tests/apc_005.phpt, tests/apc_005b.phpt, tests/apc_005c.phpt, tests/apc_006.phpt, tests/apc_006_php73.phpt, tests/apc_007.phpt, tests/apc_008.phpt, tests/apc_010.phpt, tests/apc_011.phpt, tests/apc_012.phpt, tests/apc_013_exists.phpt, tests/apc_014_store_ref.phpt, tests/apc_099.phpt, tests/apc_entry_001.phpt, tests/apc_inc_perf.phpt, tests/iterator_001.phpt, tests/iterator_002.phpt, tests/iterator_003.phpt, tests/iterator_004.phpt, tests/iterator_005.phpt, tests/iterator_006.phpt, tests/iterator_008.phpt, tests/iterator_009.phpt
Additionally perform some test cleanup.
=> Improve iterator fix

apc_cache.c, apc_cache_api.h, apc_iterator.c, apc_pool.c, apc_pool_api.h
When fetching from the cache we currently allocate an unused memory pool with an "unpool" implementation. Stop doing that. Also drop the unpool, consolidate everything into one implementation, remove some no longer generality and indirection.
=> Remove unpool

apc_iterator.c, apc_iterator.h, php_apc.c
* Preallocate all the used strings, so they are not allocated anew for every single entry.
* Allow the PCRE JIT to be used (only relevant for PHP <= 7.2, on master it was already used) for the search regex.
=> Improve APC iterator performance

apc_cache.c, apc_pool.c, apc_pool_api.h
This reduces the size of the pool by 24 bytes and each pool block by 8 bytes.
=> Optimize pool structures

apc_cache.c, apc_pool.c, apc_pool_api.h
This reduces the size of a pool by another 24 bytes, as well as performing some related cleanups.
=> More pool memory optimizations

apc_cache.c, apc_lock.c, apc_lock_api.h, apc_sma.c, config.m4
Avoid performing a double unlock if we run into EDEADLK situation. Log a warning if this occurs.
=> Check wlock return values

config.m4
Hello,
Autoconf made several macros obsolete including the `AC_TRY_COMPILE`, `AC_TRY_LINK`, and `AC_TRY_RUN` around 2000 since Autoconf 2.50:
http://git.savannah.gnu.org/cgit/autoconf.git/tree/ChangeLog.2
These macros should be replaced with the current `AC_FOO_IFELSE` macros instead.
It is fairly safe to upgrade and take the recommendation advice of autoconf upgrade manual since the upgrade should be compatible at least with PHP versions 5.4 and up, on some systems even with PHP 5.3. PHP versions from 5.4 to 7.1 require Autoconf 2.59+ and PHP 7.2+ require Autoconf 2.64+.
This patch was created with the help of the autoupdate script:
```bash
autoupdate config.m4
```
Reference docs:
- https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Obsolete-Macros.html
- …
=> Replace obsolete AC_TRY_FOO with AC_FOO_IFELSE

tests/server_test.inc
`TEST_PHP_ARGS` is used to pass args to run-tests.php, they should not be passed directly to PHP itself. CI doesn't use this so it can be removed.
Also update bc submodule to latest upstream version to ensure tests pass when `git clone --recursive` is used.
=> Don't pass PHP_TEST_ARGS through to test child processes

apc_persist.c
Optimize the unpersisting procedure, especially for arrays.
The main optimization is to avoid memcpying the array data buffer and instead copy it manually. Previously this fell through to the unaligned AVX memmove implementation, which appears to be unusually slow
=> Optimize unpersisting

apc_cache.c, apc_mmap.c, apc_shm.c, tests/not_enough_shm.phpt
* Use `E_CORE_ERROR` to make sure startup is aborted -- otherwise we would segfault lateron.
* Print a better error message, including the size of the allocation.
=> Improve mmap error handling

apc_persist.c, php_apc.c, tests/apc_store_reference.phpt
Make sure top-level values are not references (this can cause issues if the value is returned from apcu_fetch, which violated PHP's reference return semantics). Furthermore use GC_ARRAY to mark returned arrays as GC collectible.
=> Some fixes to persistence

apc_sma.c, tests/sma001.phpt
Instead of picking the first fitting block, check if there is
a smaller block that still fits. We only look at a limited, small
number of additional blocks. This is an approximation of best-fit
allocation.
This is intended to reduce fragmentation, in particular for the
case where a large block was recently freed (and is on top of the
free list) and a small allocation is performed.
=> Try to reduce SMA fragmentation

apc_lock.c, apc_mmap.c
@nikic can you please have a look at mktemp usage which is strongly discouraged
I was able to fix 1 case, but unable to test it... can't find the bulid option to use this part of code... :(
Main issue is with apc_mmap.c, as only the name is needed and don't need to be a real path, can't find a "simple" fix for this one...
=> use mkstemp instead of mktemp

apc.php
Hi, I've changed some PHP keywords to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!
=> Change PHP keywords to comply with PSR2

apc_cache.c, apc_sma.c
The apcu extension does not compile on the current php master due to the removal of uint and ulong types.
See [the revelant commit](https://github.com/php/php-src/commit/bebcdcc74573b015c22238dbc9b2698c88b7a601).
And fixed another size_t/unsigned int conversion warning.
=> Removed deprecated uint and ulong types to conform to php master (8.0)

apc_iterator.c, apc_iterator.h
The PCRE extension is always available in recent PHP 7.x versions. And HAVE_PCRE symbol is removed since PHP 8.0.
=> Remove usage of HAVE_PCRE

apc_lock_api.h, php_apc.c, tests/apc_012.phpt
This also changes apcu_inc/dec to wrap around on overflow, instead of saturating to a float value.
Fixes #343.
=> Implement apcu_inc/dec using atomic operations

php_apc.c
The default used to be 1, which meant that the effective TTL upon storing and fetching keys was backdated to the beginning of the web request.
This means values are not stored as long as users might expect, and might also appear valid longer than expected.
For example, during POST request that 2s and stores a value in APCu with a TTL of 500ms, the value effectively can't be re-used by other requests as 0.5 - 2 <= 0.
Closes https://github.com/krakjoe/apcu/issues/391.
=> Set apc.use_request_time=0 by default

.appveyor/build.ps1, .appveyor/install.ps1, .appveyor/package.ps1, .appveyor/test.ps1, appveyor.yml, tests/server_test.inc
This PR is mainly about updating the PHP versions for the builds (was 7.0-7.2, now 7.2-7.4), but also improves maintainability of the AppVeyor script, and fixes the test failures on PHP 7.4.
=> Improve and update AppVeyor CI integration

apc.php
Fixes #408
Looks like the problem was there for a while, but in PHP 8.0 `DivisionByZeroError` is fatal, which can become a little bit annoying.
=> Fix division by zero error in apc.php

apc.php
The apc.php APCu status page is great for debugging and testing, but if you ever expand a big cache entry, it's annoying because you have to scroll up and reload the page and waste clicks and time and lose your place.  This tiny patch makes it so you can click on either the row with the cache entry, or just click on the data, and it'll remove the detail.  It does this by just using the urls and refetching so it doesn't need any javascript or css stuff.  It's super hand, hope you like it!
=> Clicking on detailed user cache entry expansions closes them.

config.m4
Fix `--enable-apcu-rwlocks` which is currently disabling rwlocks
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> config.m4: fix --enable-apcu-rwlocks

.github/workflows/config.yml
That should fix the currently failing CI build.
=> Update cmb69/setup-php-sdk to v0.6

.appveyor/install.ps1
PHP 7.3 is EOL, so the builds have been moved to the archives; we need
to cater to that.
---
An alternative might be to drop AppVeyor CI in favor of GH actions altogether.
=> Fix AppVeyor CI build for PHP 7.3

apc_persist.c, package.xml, tests/apcu_fetch_empty_array_reference.phpt
Instead of allocating brand new arrays or looking them up in the hash map, return php's shared immutable empty array starting in php 7.3.
For #323
=> Reuse the immutable empty array in apcu_fetch

apc_persist.c, tests/apc_025.phpt, tests/server_test.inc
Starting in php 8.2, zvals are stored instead of Buckets, halving the memory usage per extra element. Use the same memory allocation when unserializing data and when storing data in shared memory in php 8.2.
This was previously copying too much data when there was an associative array instead of a list, and apc_025.phpt would fail with valgrind.
Related to #323
=> Fix bug in serializing php 8.2 lists, reduce memory usage.

package.xml
Note that the bug fixed in #459 could cause crashes in PHP 8.2+ with
`apc.serializer=default` (not the default) if the memory of the array
being serialized wasn't readable.
=> Add release notes and test file to package.xml

apc_iterator.c, apcue/apcue.c, php_apc.c
https://github.com/php/php-src/blob/master/docs/parameter-parsing-api.md
I used very simple and naive way to get some idea of performance improvements:
```
<?php
$ts = microtime(true);
$r1 = apcu_store('test_key', 'test_value');
var_dump($r1);
for ($i = 0; $i < 10_000_000; $i++) {
$r2 = apcu_fetch('test_key');
}
var_dump($r2);
printf("%0.6f\n", microtime(true) - $ts);
```
Before: 
```
bool(true)
string(10) "test_value"
3.218031
bool(true)
string(10) "test_value"
3.236936
bool(true)
string(10) "test_value"
3.164991
bool(true)
string(10) "test_value"
3.315372
```
After:
```
bool(true)
string(10) "test_value"
2.996424
bool(true)
string(10) "test_value"
2.872444
bool(true)
string(10) "test_value"
2.991932
bool(true)
string(10) "test_value"
2.961243
```
=> Switch to modern parameters parsing API

.editorconfig, apc_mutex.h, config.m4
https://editorconfig.org/ has integrations with many editors/IDEs to apply project-specific settings (e.g. to consistently use tabs)
https://www.php-fig.org/psr/psr-12/ recommends using spaces for php code. (though many of these tests use tabs, I don't have a strong preference)
Replace the mix of tabs and spaces in config.m4 with spaces.
=> Add editorconfig file for APCu

apc.h
This was removed from the implementation long ago. See "Remove experimental eval serializer" in package.xml
=> Remove eval serializer name from header

apc.php
On tabs other than "User Cache Entries", don't fetch metadata about cache entries.
When running php apc.php in CLI to preview this (adding a cached entry),
I noticed a DivisionByZeroError this fixes.
For https://github.com/krakjoe/apcu/issues/365
https://www.php.net/manual/en/function.apcu-cache-info.php#refsect1-function.apcu-cache-info-changelog 
I previewed this in cli for convenience by using the environment instead of an http request
`for IMG in {1..3}; do export IMG; php apc.php > $IMG.png; done` - the image generation doesn't use apcu_cache_info.
```diff
--- a/apc.php
+++ b/apc.php
@@ -95,6 +95,10 @@ $scope_list=array(
'A' => 'cache_list',
'D' => 'deleted_list'
);
+$_REQUEST = $_ENV;
+for ($i = 0; $i < 21; $i++) {
+       apcu_store("k$i", str_repeat('x', 2**$i));
+}
```
=> Reduce memory usage of apc.php. Fix division by zero error.

apc_cache.c
zend_long is signed, and on some configurations potentially not equal in width to the z specifier. Use ZEND_LONG_FMT instead.
=> Use the correct format string for zend_long

tests/server_test.inc
Needed when building out of sources because of `"-d extension_dir=$doc_root/../modules"`
Allow to run:
```
TEST_PHP_ARGS="-n -d extension=$BUILDDIR/modules/apcu.so"  php  run-tests.php --show-diff
```
No change for people building in sources tree and using "make test"
=> use TEST_PHP_ARGS if set

tests/apc54_014.phpt, tests/ghbug176.phpt
PHP 8.4 changed the PHP_ZTS constant to bool: https://github.com/php/php-src/pull/13079
As a result, the tests that fail with ZTS would no longer be skipped.
=> tests: Fix PHP ZTS detection

config.m4
This replaces the "hacky" Makefile variable usage in config.m4 with a regular shell variable.
Issue initially noted at https://github.com/php/php-src/pull/15642
=> Autotools: Replace APCU_CFLAGS Makefile variable with shell variable

config.m4
- Instead of AC_ARG_ENABLE the PHP_ARG_ENABLE works in similar manner and outputs the 2nd argument as the check message. Result variable is the same (PHP_APCU_RWLOCKS). By default the option is enabled like before. The 4th argument sets whether the option is enabled, the 5th argument indicates that this is not direct extension related configuration option (build system internal handling stuff).
- AC_CACHE_CHECK check refactored: Entire check moved inside the main "extension-enabled" if block, AS_VAR_IF used, redundant double Autoconf quotes reduced.
- AC_MSG_FAILURE works the same as AC_MSG_ERROR except that it also outputs the "See config.log for details" message at the end in case of failure, directing the user where to check for possible failure reason.
=> Autotools: Refactor --enable-apcu-rwlocks option to PHP_ARG_ENABLE

config.m4
The HAVE_SEMUN usage was removed via
fcf43c91206c354d2db4e171e9f7fa471512cb19 and the check is redundant at this point.
=> Autotools: Remove union semun check

config.m4
- This uses the PHP_ARG_ENABLE instead of core AC_ARG_ENABLE to have check message automatically output and result variable PHP_APCU_SPINLOCKS set.
- AS_VAR_IF used
- AC_DEFINE arguments quoted and some simplistic help message text added.
=> Autotools: Refactor --enable-apcu-spinlocks

apc_cache.c, apc_signal.c, apc_sma.c, php_apc.c
- ZTS
- PHP_WIN32
- HAVE_SIGACTION
are either undefined or defined to 1. This fixes possible -Wundef (Windows C4668 warning code) warnings if such compiler configuration is set.
=> Fix -Wundef warnings

apc_cache.c, apc_globals.h, apc_mmap.c, apc_mmap.h, apc_sma.c, config.m4, php_apc.c
- AC_ARG_ENABLE replaced with PHP_ARG_ENABLE
- checks sorted
- AS_VAR_IF macros used
- For checking the Valgrind header, the AC_CHECK_HEADERS is used which defines the HAVE_VALGRIND_MEMCHECK_H preprocessor macro by default
- The APC_MMAP preprocessor macro is either undefined or defined to 1 so the `#if` checks are also replaced with `#ifdef` to not cause possible -Wundef warnings emitted if such compiler configuration is set
=> Autotools: Sync configure options

config.m4
This appends the -lrt only as needed to the LIBS (if apcu is built as static) or to the APCU_SHARED_LIBADD variable (when APCu is built as shared). Modern *nix systems have shared memory operations located in default libraries and explicit linking with -lrt is redundant.
~Edit: fixing this for the case when shm_open isn't found...~
=> Autotools: Refactor rt library check

.github/workflows/config.yml
We also change the setup-php-sdk branch to a commit on the main branch. This should be changed again when a new setup-php-sdk release is made.
=> Run Windows CI against PHP 8.4, too

.github/workflows/config.yml
As of actions/upload-artifact@v4, hidden files are excluded from uploading by default, so the `.install` folder is no longer uploaded. Instead of changing the default, we change the name of the folder to `win-install` which generally appears to make more sense than a hidden folder.
=> Fix Windows CI artifact upload

apc_cache.c
If the runtime configuration setting apc.ttl is 0 (default value), the function apc_cache_default_expunge() always uses a real expunge and throws away tho whole cache content, even though this is unnecessary and not the documented behavior. 
The documentation for apc.ttl says (see https://www.php.net/manual/en/apcu.configuration.php):
"... This setting has no effect on cache entries that have an explicit TTL specified." 
The expected behavior is that entries with explicit TTL should be cleaned up first and only if this is insufficient a real expunge should be performed (independent of how apc.ttl is set).
Because apc_cache_entry_expired() takes care of the global apc.ttl setting, no special case is needed for apc.ttl == 0 in apc_cache_default_expunge(). For this reason the code in …
=> Try to cleanup cache entries with explicit ttl when apc.ttl is 0

apc_sma.c, apc_sma.h, tests/apc_020.phpt
apc_sma_get_avail_size() is used by apc_cache_default_expunge() to check whether enough memory is available to store a new cache entry after expired entries are removed. If there is not enough memory available, a real expunge is performed to be able to store the new entry.
The problem is that apc_sma_get_avail_size() only checks the total amount of available memory, which is usually divided into several fragments of memory. However, we need a contiguous block of memory to store a cache entry.
This pull request fixes apc_sma_get_avail_size() to check if a continuous block of memory is available to store a new entry, which solves the problem.
Prior to this fix, the result was that in situations with fragmentation, new cache entries cannot be saved and PHP functions such as apcu_store() …
=> Fix apc_sma_get_avail_size() to look for a contiguous block of memory to make expunge more reliable

apc_sma.c
The size passed to expunge() must match the size passed to find_block().
=> Fix required memory size passed to expunge()

config.m4
This fixes compiler warnings in out-of-tree builds.
Closes #521
=> config.m4: Add -Wno-clobbered to fix compiler warnings

apc_cache.c
By default (apc.smart = 0), apc_cache_default_expunge() should not skip cleanup of old entries. This may cause insertion of new entries to fail unnecessarily, which is unexpected behavior.
=> Cleanup of entries should not be skipped when using default settings

apc_cache.c, apc_cache.h
The smart configuration setting can now be used to increase the chance of full cache wipes during periods of high memory pressure. The idea is to use smart values > 1 to avoid performance problems when the expunge() hook is executed too often. The previous behavior was changed because it could unpredictably cause the insertion of new cache entries to fail, making the smart setting nearly useless.
=> Change behavior of smart configuration setting

apc_cache.h, apc_sma.c, apc_sma.h, php_apc.c
The minimum fragment size previously used by the sma layer was too small. This could lead to the unnecessary creation of small free blocks that could not be used for any allocation. To keep separation of layers, the minimum size is now passed to apc_sma_init().
=> Fix computation of minimum fragment size

TECHNOTES.txt, apc_cache.c, apc_cache.h
The "state" variable was unused and shmaddr pointed to the same address as header.
=> Remove unnecessary variables from apc_cache_t and apc_cache_header_t

TECHNOTES.txt, apc_sma.c
The variables shmaddr and header were often used simultaneously in the same context, although both always pointed to the same memory address. This was because the BLOCKAT / OFFSET macros expected shmaddr to be present and header was used to access data of the header struct. Now the variable smaheader is used for both.
=> Unify shmaddr and header in sma layer

apc_sma.c
Prevent misalignment of the last (0-sized) block when using an unaligned size as configuration value for apc.shm_size (e.g. 1048577).
=> Use aligned size for shm to ensure alignment of last block in sma layer

apc_sma.h
ALIGNWORD() now redefines ZEND_MM_ALIGNED_SIZE(), which PHP itself uses to align data structures. It's better optimized and allows the compiler to generate faster code. It also makes sense to use the same alignment in APCU as in PHP.
=> Optimize ALIGNWORD()

apc_sma.c
The sum of the size of all free blocks is now in sync with smaheader->avail. Additionally, this fixes the position of the last (0-sized) block. Before this change, ALIGNWORD(sizeof(block_t)) bytes remained free at the end of the shared memory.
=> Fix size of initial empty block in sma layer

apc_globals.h, apc_sma.c, apc_sma.h, php_apc.c, tests/apcu_sma_info.phpt
The support for multiple shared memory segments is not necessary these days, as systems that suffered from shared memory size limitations now use mmap(), which is unaffected by such limitations. In addition, this simplifies the sma layer and makes it easier to refactor the cache layer so that the cache is relocatable.
=> Drop support for multiple shared memory segments

TECHNOTES.txt, apc_cache.c, apc_cache.h, apc_iterator.c, apc_persist.c, php_apc.c
The key is now implemented as the last part of apc_cache_entry_t, which is another step toward making entries relocatable in the future. Furthermore, this reduces the size of an entry by the size of a pointer and removes one memcpy() of apc_cache_entry_t during insertion.
=> Make the key of a cache entry relocatable

apc_cache.c, apc_persist.c
This makes the persistence representation of cache entries in shm position-independent by converting all pointers in an entry's zval value to offsets relative to the entry's starting address. During persistence, all (process local) pointers are converted and stored as offsets in shm. During unpersistence, the (process local) shm starting address of the entry is added to each offset before data access. This is necessary to make the whole cache relocatable or to develop defragmentation.
=> Make cache entries relocatable

apc_cache.c, php_apc.c, tests/iterator_006.phpt
The new default behavior is to use 512 slots per MB of shared memory, which keeps the hash table size < 0.4% of shm, which seems negligible. This should improve the default behavior, as it improves apcu's performance with many entries, and the hash table size now scales with the size of shared memory. Previously, a fixed value of 4096 at 32 MB shm was used as default, which corresponds to 128 slots per MB.
Closes #344
=> Compute the number of hash slots instead of using a fix default value

TECHNOTES.txt, apc_cache.c, apc_cache.h, apc_iterator.c
This makes the cache position-independent by converting all pointers to entries into offsets relative to the starting address of the cache header in the shared memory segment. This is a further step to enable the use of APCU with processes that access the shared memory segment via different starting addresses.
=> Make cache relocatable

TECHNOTES.txt, apc_cache.c, apc_cache.h, apc_sma.c, apc_sma.h, package.xml, tests/apc_defrag.phpt
This adds defragmentation logic to apcu, which is performed during the default_expunge operation. It works by shifting all allocated blocks to the left (low addresses), allowing all free blocks to be coalesced to one larger free block on the right side.
=> Add defragmentation to apcu

.github/workflows/config.yml
This requires windows-2019, which is being phased out: https://github.com/actions/runner-images/issues/12045
=> Disable Windows CI for PHP 7.x

.github/workflows/config.yml
All PHP 7.x Linux pipelines silently aborted the tests because the PHP executable could not be found. This was caused by the definition of "PHP_EXECUTABLE = NONE" in the Makefile, as "php-config --php-binary" returned "NONE" during ./configure. Since it seems time-consuming to fix the root cause, this is a temporary workaround until PHP 7.x is removed from the CI pipeline.
Closes #566
=> Fix Linux CI for PHP 7.x to not silently abort tests

apc.php, apc_cache.c, apc_cache.h, package.xml, tests/apc_defrag.phpt
The cache cleanup and defragmentation counts are now available in the array returned by apcu_cache_info().
=> Add cache cleanup and defragmentation counts to apcu_cache_info()

package.xml, tests/apc_repeated_unpersist.phpt
The purpose of this test is to ensure that the unpersist-code does not accidentally change the persistence representation in SHM (e.g., by the offset -> pointer conversion), causing a second unpersist to fail.
=> Add test that a repeated unpersist doesn't break representation

apc_cache.c, apc_cache.h, apc_sma.c, apc_sma.h
Under high load, multiple parallel insert operations could trigger multiple default expunge operations at the same time. To prevent this, pending default expunge operations are now aborted if another default expunge operation has run in the meantime.
=> Fix stacking of default expunge operations

apc_cache.c, apc_persist.c, apc_sma.c, apc_sma.h
This fixes a race condition that can occur when a newly allocated entry is moved by defragmentation before it is inserted into the hash table.
=> Fix race condition during allocation / defragmentation

apc_cache.c
In apc_cache_store(), the ref_count was decremented even when the entry needed to be deleted. This allowed the entry to be moved by defragmentation (by another process) before deletion. As a result, the pointer no longer pointed to the desired entry during deletion, causing segmentation faults.
=> Fix releasing of ref_count in apc_cache_store()
